//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Resources.Mail.Index {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("test.Resources.Mail.Index.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateBy.
        /// </summary>
        public static string CreateBy {
            get {
                return ResourceManager.GetString("CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateTime.
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Content.
        /// </summary>
        public static string EmailContent {
            get {
                return ResourceManager.GetString("EmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Attach.
        /// </summary>
        public static string FileAttach {
            get {
                return ResourceManager.GetString("FileAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Send.
        /// </summary>
        public static string IsSend {
            get {
                return ResourceManager.GetString("IsSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn About.
        /// </summary>
        public static string LearnAbout {
            get {
                return ResourceManager.GetString("LearnAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List mails.
        /// </summary>
        public static string MailList {
            get {
                return ResourceManager.GetString("MailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mail.
        /// </summary>
        public static string NewMail {
            get {
                return ResourceManager.GetString("NewMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filters.
        /// </summary>
        public static string SearchFilters {
            get {
                return ResourceManager.GetString("SearchFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Status.
        /// </summary>
        public static string SendStatus {
            get {
                return ResourceManager.GetString("SendStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Time.
        /// </summary>
        public static string SendTime {
            get {
                return ResourceManager.GetString("SendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range.
        /// </summary>
        public static string TimeRange {
            get {
                return ResourceManager.GetString("TimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Type.
        /// </summary>
        public static string TimeType {
            get {
                return ResourceManager.GetString("TimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
    }
}
